queue_rules:
  - name: main-queue
    autoqueue: true
    queue_conditions:
      - and:
          - label = ready
    branch_protection_injection_mode: merge
    merge_conditions:
      - and:
          - check-success = continuous-integration/travis-ci
pull_request_rules:
  - name: Automatically queue PRs when approved and CI passes
    conditions:
      - "#approved-reviews-by>=1"
      - check-success=tests
      - label!=do-not-merge
    actions:
      queue:
        name: default
  - name: Delete branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch: {}
