queue_rules:
  - name: default
    merge_conditions:
      - check-success=tests
    autoqueue: true
    queue_conditions:
      - and:
          - label = ready
          - check-success = tests
pull_request_rules:
  - name: Automatically queue PRs when approved and CI passes
    conditions:
      - "#approved-reviews-by>=1"
      - check-success=tests
      - label!=do-not-merge
    actions:
      queue:
        name: default
  - name: Delete branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch: {}
